
GET http://localhost:8000/ok/

###
GET http://localhost:8000/books



###

GET http://localhost:8000/metrics

###

GET http://localhost:8000/books

###

POST http://localhost:8000/books
Content-Type: application/json

{
    "title": "tumbolisiloshiba",
        "author": "Assumpta kesi",
        "publicationYear": 2001
}



###
DELETE http://localhost:8000/books/1





