
GET http://localhost:8000/api/ok/

###
GET http://localhost:8000/api/books



###

GET http://localhost:8000/api/metrics

###

GET http://localhost:8000/api/books

###

POST http://localhost:8000/api/books
Content-Type: application/json

{
    "title": "kigogo",
        "author": "Assumpta kesi",
        "publication_year": 2001
}



###
DELETE http://localhost:8000/api/books/1





